version: "2"
services:
    app1:
        image: python:3-alpine
        expose:
            - 8000
        volumes:
            - ./app:/app
        command: python /app/app.py
        environment:
            - NAME="First"
        networks:
            my_net:
              ipv4_address: 10.0.0.10
    app2:
        extends:
            service: app1
        environment:
            - NAME="Second"
        networks:
            my_net:
              ipv4_address: 10.0.0.20
    web:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - app1
            - app2
        ports:
            - "8800:80"
        networks:
            my_net:
              ipv4_address: 10.0.0.90
networks:
    my_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/24